// Flutter icons Custom
// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  Custom
//      fonts:
//       - asset: fonts/Custom.ttf
//
//
// * Font Awesome, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL ()
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
//
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData docs = IconData(0xf0c5, fontFamily: _kFontFam);
  static const IconData tumblr = IconData(0xf173, fontFamily: _kFontFam);
  static const IconData share = IconData(0xf1e0, fontFamily: _kFontFam);
  static const IconData pinterest = IconData(0xf231, fontFamily: _kFontFam);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData linkedin_squared =
      IconData(0xf30c, fontFamily: _kFontFam);
}
